AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  MTXML API

Globals:
  Function:
    Timeout: 10

Resources:
  MtXmlGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan to MTXML API
          Quota:
            Limit: 100
            Period: DAY
          Throttle:
            BurstLimit: 1
            RateLimit: 1
          UsagePlanName: MTXML Usage plan
  MtXmlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.mtxml.App::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /mttoxml
            Method: get
            RestApiId:
              Ref: MtXmlGatewayApi


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MtXmlGatewayApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${MtXmlGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/mtxml/"
  MtXmlFunction:
    Description: "MT to XML Lambda Function ARN"
    Value: !GetAtt MtXmlFunction.Arn
  MtXmlFunctionIamRole:
    Description: "Implicit IAM Role created for mtxml Lambdas"
    Value: !GetAtt MtXmlFunctionRole.Arn
